language: java
dist: xenial
install: true

jdk:
  - openjdk8
before_install:
- openssl aes-256-cbc -K $encrypted_8fd383601570_key -iv $encrypted_8fd383601570_iv
   -in application.properties.enc -out ./src/main/resources/application.properties -d

services:
  - docker

script:
  - ./gradlew --refresh-dependencies clean build
  - docker login --username $DOCKER_HUB_USER --password $DOCKER_HUB_PSW
  - docker build -t hub.docker.com/prithvi425/restaurant .
  - docker tag hub.docker.com/prithvi425/restaurant:latest prithvi425/restaurant:latest
  - docker push prithvi425/restaurant:latest

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: develop